### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by GoodGas** [TheKingOfDuck/Loki#1]
您好，这个蜜罐不适用linux系统吗

**Comment by TheKingOfDuck** [comment]
> 您好，这个蜜罐不适用linux系统吗

......

打比赛的对话闲着无聊在Windows开发了demo，后在自己的Mac上完善了功能，平时稳定的跑在Linux的服务器上. 说不支持就离谱，也不贴个报错啥的，你这让我怎么回答你...
