### ISSUE TITLE
Java 1.8 error

### ISSUE THREAD

**Issue by Ran-Xing** [TheKingOfDuck/Loki#2]
```ini
➜ loki
➜ loki java -jar loki.jar
██╗ ██████╗ ██╗ ██╗██╗ /**
██║ ██╔═══██╗██║ ██╔╝██║ * @NAME Loki
██║ ██║ ██║█████╔╝ ██║ * @VERSION 0.0.1
██║ ██║ ██║██╔═██╗ ██║ * @AUTHOR CoolCat
███████╗╚██████╔╝██║ ██╗██║ * @GITHUB https://github.com/TheKingOfDuck
```

logfile :   error.txt http://91io.cn/s/xBgK7f7/error.txt

Valid for seven days

```ini
SHA1  error.txt
0a263b05e89f91d24fa33639e47e0af1746eba98
```

**Comment by TheKingOfDuck** [comment]
> ```ini
> ```ini
> ➜ loki
> ➜ loki java -jar loki.jar
> ██╗ ██████╗ ██╗ ██╗██╗ /**
> ██║ ██╔═══██╗██║ ██╔╝██║ * @NAME Loki
> ██║ ██║ ██║█████╔╝ ██║ * @VERSION 0.0.1
> ██║ ██║ ██║██╔═██╗ ██║ * @AUTHOR CoolCat
> ███████╗╚██████╔╝██║ ██╗██║ * @GITHUB https://github.com/TheKingOfDuck
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> logfile :   error.txt http://91io.cn/s/xBgK7f7/error.txt
> Valid for seven days
> ```ini
> SHA1  error.txt
> 0a263b05e89f91d24fa33639e47e0af1746eba98
> ```
> ```

可以少监听一点端口试试
