### ISSUE TITLE
为什么无法登录后台呢

### ISSUE THREAD

**Issue by 821251775** [TheKingOfDuck/Loki#3]
下载解压idea导入后也可以运行，为啥后台页面进不去

**Comment by TheKingOfDuck** [comment]
> 下载解压idea导入后也可以运行，为啥后台页面进不去

贴一下具体的配置 jdk版本 浏览器版本。

**Comment by 821251775** [comment]
浏览器就是谷歌最新版本，jdk的话
![image](https://user-images.githubusercontent.com/40810787/134448975-f2fed48e-e7ff-4e90-a6b7-00512dbe7f7a.png)

**Comment by TheKingOfDuck** [comment]
加我wx发配置截图看看, 得自己改。。。

**Comment by 821251775** [comment]
已经登录上了，原来是我文件夹中文名字，导致一直找不到路径
