### ISSUE TITLE
网页问题

### ISSUE THREAD

**Issue by 821251775** [TheKingOfDuck/Loki#4]
我想请问一下，另外另外两个网页是打不开吗？为什么在后台管理页面看不到他们俩的尝试登录的信息呢，只能在idea里面看见一些信息变动。还有就是钓鱼页面也没有，是我配置问题什么。

**Comment by TheKingOfDuck** [comment]
> 我想请问一下，另外另外两个网页是打不开吗？为什么在后台管理页面看不到他们俩的尝试登录的信息呢，只能在idea里面看见一些信息变动。还有就是钓鱼页面也没有，是我配置问题什么。

你这光知道说打不开 截图啥的都没有一个 也不贴配置之类的 你让我咋了解问题？
